name: RealisticVillagers
version: ${project.parent.version}
author: Matsubara
main: me.matsubara.realisticvillagers.RealisticVillagers
api-version: 1.18
load: STARTUP
description: ${project.description}
depend:
  - packetevents
softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

commands:
  realisticvillagers:
    description: main command.
    usage: /<command>
    aliases:
      - rv
      - rvillagers
      - realvillagers
  gender:
    description: Change the gender of the villager you're looking at.
    usage: /gender <male|female>
    permission: realisticvillagers.gender
    permission-message: "&cYou don't have permission to use this command."

permissions:
  realisticvillagers.gender:
    description: Allows using /gender to set the gender of a villager you're looking at.
    default: op
  realisticvillagers.genderset:
    description: Allows using /rv genderset to forcibly set a villager's gender for a target player (bypasses gender lock).
    default: op